import { getDb } from "@/lib/db/client";
import { crewTaskLabel, listCrewJobs } from "@/lib/services/crew";
import { listCandidates } from "@/lib/services/candidates";
import { CrewControls } from "@/components/crew-controls";
import { Card, EmptyState, PageHeader, Tag } from "@/components/ui";

export const metadata = { title: "Crew" };

const STATUS_TONE: Record<string, "ok" | "warn" | "bad" | "neutral"> = {
  done: "ok",
  queued: "neutral",
  awaiting_model: "warn",
  critiquing: "warn",
  revising: "warn",
  failed: "bad",
  cancelled: "neutral",
};

export default async function CrewPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const db = getDb();
  const [jobs, candidates] = await Promise.all([
    listCrewJobs(db, id),
    listCandidates(db, id),
  ]);
  const candidateName = new Map(candidates.map((c) => [c.id, c.name]));
  const active = jobs.filter((j) =>
    ["queued", "awaiting_model", "critiquing", "revising"].includes(j.status),
  );
  const pendingHandoffs = active.filter((j) => j.requestPath);
  const latestRun = jobs.filter((j) => j.status !== "cancelled");

  return (
    <div>
      <PageHeader
        title="Crew"
        description="A per-search team of specialist agents: each module is generated by a role-scoped agent, reviewed by a critic, and revised once when the critic finds concrete defects. Every result lands as an editable draft with the usual provenance, fair-hiring scan, and audit trail — agents draft, you decide."
        actions={
          <CrewControls projectId={id} hasActiveJobs={active.length > 0} />
        }
      />

      {pendingHandoffs.length > 0 && (
        <Card title="Waiting on a Claude session">
          <p className="text-[13px] text-ink-muted">
            The session provider parked {pendingHandoffs.length} generation
            {pendingHandoffs.length === 1 ? "" : "s"} on request files. Open
            Claude Code in this repo and say{" "}
            <span className="text-ink">
              “fulfill the pending crew requests, then advance the crew”
            </span>{" "}
            — or run <code className="text-[12px]">pnpm crew:work</code> with an
            API key configured.
          </p>
          <ul className="mt-2 space-y-1 text-[12px] text-ink-faint">
            {pendingHandoffs.map((j) => (
              <li key={j.id} className="font-mono">
                {crewTaskLabel(j.task)}: {j.requestPath}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {latestRun.length === 0 ? (
        <EmptyState
          title="No crew yet"
          detail="Kick off the crew to queue the nine project agents (role intelligence through interview plan). Candidate agents queue from each candidate's page."
        />
      ) : (
        <div className="mt-4 space-y-2">
          {latestRun.map((job) => (
            <div
              key={job.id}
              className="flex items-start gap-3 rounded border border-edge bg-panel px-4 py-3"
            >
              <div className="w-44 shrink-0">
                <div className="text-[13px] font-semibold">
                  {crewTaskLabel(job.task)}
                </div>
                {job.candidateId ? (
                  <div className="text-[11.5px] text-ink-muted">
                    {candidateName.get(job.candidateId) ?? "candidate"}
                  </div>
                ) : null}
              </div>
              <Tag tone={STATUS_TONE[job.status] ?? "neutral"}>
                {job.status.replace("_", " ")}
              </Tag>
              <div className="min-w-0 flex-1 text-[12.5px] text-ink-muted">
                {job.error ? (
                  <span className="text-bad">{job.error}</span>
                ) : job.critique ? (
                  <div>
                    <span
                      className={
                        job.critique.verdict === "revise"
                          ? "text-warn"
                          : "text-ok"
                      }
                    >
                      critic: {job.critique.verdict}
                    </span>
                    {job.critique.issues.length > 0 && (
                      <ul className="mt-1 list-disc pl-4">
                        {job.critique.issues.map((issue) => (
                          <li key={issue}>{issue}</li>
                        ))}
                      </ul>
                    )}
                  </div>
                ) : job.status === "queued" && job.dependsOn.length > 0 ? (
                  <span>
                    waits on {job.dependsOn.map(crewTaskLabel).join(", ")}
                  </span>
                ) : null}
              </div>
              <div className="shrink-0 text-right text-[11px] text-ink-faint tabular-nums">
                {job.attempt > 0
                  ? `${job.attempt} pass${job.attempt === 1 ? "" : "es"}`
                  : ""}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
