"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { GenerationMeta } from "@/lib/core/enums";
import { saveArtifactJsonAction } from "@/lib/actions/workflow";
import { MockBadge } from "./ui";

export type ArtifactKind =
  | "role_intelligence"
  | "success_profile"
  | "market_research"
  | "sourcing_strategy"
  | "screen_guide"
  | "interview_plan"
  | "intake"
  | "evidence"
  | "close_plan"
  | "onboarding_plan";

/**
 * Attribution bar for a generated artifact: provider/model/when, MOCK
 * watermark, and the universal "Edit JSON" affordance — every AI draft is
 * editable, validated by its own schema on save.
 */
export function ArtifactMeta({
  meta,
  kind,
  ownerId,
  payload,
}: {
  meta: GenerationMeta | null;
  kind: ArtifactKind;
  ownerId: string;
  payload: unknown;
}) {
  const [editing, setEditing] = useState(false);
  const [text, setText] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const router = useRouter();

  return (
    <div className="mb-3 flex flex-wrap items-center gap-2 text-[11.5px] text-ink-faint">
      {meta ? (
        <>
          {meta.provider === "mock" && <MockBadge />}
          <span>
            Generated by {meta.provider === "mock" ? "mock provider" : meta.model}{" "}
            · {new Date(meta.generatedAt).toLocaleString()}
          </span>
        </>
      ) : (
        <span>No generation metadata.</span>
      )}
      <button
        type="button"
        className="rounded border border-edge2 px-2 py-0.5 text-[11px] text-ink-muted hover:bg-panel2"
        onClick={() => {
          setText(JSON.stringify(payload, null, 2));
          setError(null);
          setEditing(true);
        }}
      >
        Edit JSON
      </button>
      {editing && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-8"
          onClick={() => setEditing(false)}
        >
          <div
            className="flex h-full w-full max-w-3xl flex-col rounded-lg border border-edge2 bg-panel p-4"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-2 flex items-center justify-between">
              <span className="text-[13px] font-medium text-ink">
                Edit artifact ({kind}) — validated against its schema on save
              </span>
              <button
                type="button"
                className="text-[12px] text-ink-faint hover:text-ink"
                onClick={() => setEditing(false)}
              >
                Close
              </button>
            </div>
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              spellCheck={false}
              className="min-h-0 flex-1 resize-none rounded border border-edge bg-canvas p-3 font-mono text-[12px] text-ink outline-none"
            />
            {error && (
              <p className="mt-2 rounded border border-bad/40 bg-bad-soft px-3 py-2 text-[12px] text-bad">
                {error}
              </p>
            )}
            <div className="mt-3 flex justify-end gap-2">
              <button
                type="button"
                disabled={pending}
                onClick={() =>
                  startTransition(async () => {
                    const result = await saveArtifactJsonAction({
                      kind,
                      ownerId,
                      json: text,
                    });
                    if (result.ok) {
                      setEditing(false);
                      router.refresh();
                    } else {
                      setError(result.error);
                    }
                  })
                }
                className="rounded bg-accent px-3 py-1.5 text-[13px] font-medium text-canvas disabled:opacity-50"
              >
                {pending ? "Saving…" : "Save"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
