import type { Certainty, ProvenanceSource } from "@/lib/core/enums";
import { PROVENANCE_LABELS } from "@/lib/core/enums";

export function PageHeader({
  title,
  description,
  actions,
}: {
  title: string;
  description?: React.ReactNode;
  actions?: React.ReactNode;
}) {
  return (
    <div className="mb-5 flex items-start justify-between gap-4">
      <div>
        <h1 className="text-lg font-semibold">{title}</h1>
        {description && (
          <p className="mt-1 max-w-2xl text-[13px] text-ink-muted">
            {description}
          </p>
        )}
      </div>
      {actions && (
        <div className="flex shrink-0 items-center gap-2">{actions}</div>
      )}
    </div>
  );
}

export function Card({
  title,
  children,
  className = "",
}: {
  title?: React.ReactNode;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <section
      className={`rounded-lg border border-edge bg-panel p-4 ${className}`}
    >
      {title && (
        <h2 className="mb-3 text-[13px] font-semibold text-ink">{title}</h2>
      )}
      {children}
    </section>
  );
}

export function EmptyState({
  title,
  detail,
  children,
}: {
  title: string;
  detail?: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="rounded-lg border border-dashed border-edge2 bg-panel/50 px-6 py-10 text-center">
      <p className="text-sm font-medium text-ink">{title}</p>
      {detail && (
        <p className="mx-auto mt-1 max-w-md text-[13px] text-ink-muted">
          {detail}
        </p>
      )}
      {children && (
        <div className="mt-4 flex justify-center gap-2">{children}</div>
      )}
    </div>
  );
}

const BADGE_BASE =
  "inline-flex items-center rounded px-1.5 py-px text-[10.5px] font-medium tracking-wide";

export function ProvenanceBadge({ source }: { source: ProvenanceSource }) {
  const styles: Record<ProvenanceSource, string> = {
    jd: "bg-panel2 text-ink-muted",
    hiring_manager: "bg-accent-soft text-accent",
    recruiter: "bg-ok-soft text-ok",
    market_research: "bg-panel2 text-ink-muted",
    model_inference: "bg-warn-soft text-warn",
    source_verified: "bg-ok-soft text-ok",
  };
  return (
    <span className={`${BADGE_BASE} ${styles[source]}`} title="Provenance">
      {PROVENANCE_LABELS[source]}
    </span>
  );
}

export function CertaintyBadge({ certainty }: { certainty: Certainty }) {
  const styles: Record<Certainty, string> = {
    verified: "bg-ok-soft text-ok",
    estimated: "bg-warn-soft text-warn",
    inferred: "bg-warn-soft text-warn",
    unknown: "bg-panel2 text-ink-faint",
  };
  return (
    <span className={`${BADGE_BASE} ${styles[certainty]}`} title="Certainty">
      {certainty}
    </span>
  );
}

export function Tag({
  children,
  tone = "neutral",
}: {
  children: React.ReactNode;
  tone?: "neutral" | "accent" | "ok" | "warn" | "bad";
}) {
  const styles = {
    neutral: "bg-panel2 text-ink-muted",
    accent: "bg-accent-soft text-accent",
    ok: "bg-ok-soft text-ok",
    warn: "bg-warn-soft text-warn",
    bad: "bg-bad-soft text-bad",
  };
  return <span className={`${BADGE_BASE} ${styles[tone]}`}>{children}</span>;
}

export function MockBadge() {
  return (
    <span
      className={`${BADGE_BASE} border border-warn/40 bg-warn-soft text-warn`}
      title="Generated by the mock provider — deterministic fixture output, not real analysis."
    >
      MOCK
    </span>
  );
}

export function KeyValue({
  label,
  value,
}: {
  label: string;
  value: React.ReactNode;
}) {
  if (value === undefined || value === null || value === "") return null;
  return (
    <div className="flex gap-2 text-[13px]">
      <span className="w-40 shrink-0 text-ink-faint">{label}</span>
      <span className="min-w-0 text-ink">{value}</span>
    </div>
  );
}
